config/routes.rb
Rails.application.routes.draw do
  devise_for :admins,controllers:{sessions:"admin/sessions"}
  devise_for :users,controllers:{sessions:"user/sessions"}
  get 'order_details/new'

  get 'order_details/show'

  get 'order_details/destroy'

  get 'payment/send'

  get 'payment/receive'
    
  resources :posts do
      resources :comments
  end
    root 'posts#index'
    
    get '/gabriel' , to: 'posts#new'
    get '/post_create', to: 'posts#create'

end

app/models/post.rb
class Post < ActiveRecord::Base
    has_many :comments
    belongs_to :user
    validates_presence_of :title, :message => "Tienes que poner un titulo"
    validates_length_of :body, :in=> 10..400, :message =>"Longitud no valida" 
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	#protect_from_forgery with: :excep =>[:index,:create]
	protect_from_forgery :except => [:index, :create]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
 # def index
  #    @posts = Post.all
  #end

  def index 
  	if admin_signed_in?
          @posts =Post.all
            respond_to do |format|
                format.json do
                    render :json => @posts, :callback => params[:callback]
                end
                format.html
            end
        end
      if user_signed_in?
          @posts = current_user.posts
            respond_to do |format|
                format.json do
                    render :json => @posts, :callback => params[:callback]
                end
                format.html
            end
        end
  end

  def show
  end

  # GET /posts/new
  def new
    @post = Post.new

  end

  # GET /posts/1/edit
  def edit
    user_signed_in?
      if cannot? :edit,@post
        flash[:alert] = "NO TIENES PERMISO PARA EDITAR"
          redirect_to :action =>'index'
      end
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    
    respond_to do |format|
      if @post.save
       # Correo.bienvenida(current_user).deliver_now
        flash[:success] = "El post se guardó correctamente"
        format.html { redirect_to @post }
        #format.json { render :show, status: :created, location: @asesoria }
          format.json do
            render :json => @post, :callback => params[:callback]
          end
      else
        #format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        flash[:success] = "El post se modificò correctamente"
        format.html { redirect_to @post}
        format.json { render :show, status: :ok, location: @post }
      else
        flash[:error] = "El post no se pudo modificar"
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      flash[:success]="Se eliminò correctamente el post"
      format.html { redirect_to posts_url}
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
    	params.require(:post).permit( :title, :body, :categoria, :user_id) 
    end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="row">
  <div class="field small-6 columns">
    <%= f.label :title %><br>
    <%= f.text_field :title, :class => "validate[required]" %>
  </div>
  <div class="field small-6 columns">
    <%= f.label :body %><br>
    <%= f.text_area :body, :class => "validate[required]" %>
  </div>
   <div class="field small-6 columns">
   <% categorias = {
    "Alimentos" => "Alimentos",
    "Deportes" => "Deportes",
    "Espectáculos" => "Espectáculos",
    "Mascotas" => "Mascotas",
    "Sociedad" => "Sociedad", 
    "Tecnologia" => "Tecnologia",
   } %>
    <%= f.label :categoria %><br>
    <%= f.select :categoria, categorias, :class => "validate[required]" %>
  </div>
  <%= f.hidden_field :user_id,{ :value => current_user.id } %>
  <div class="actions">
    <%= f.submit 'Aceptar',:class => 'button small round' %>
  </div>
     
</div>
<% end %>

app/views/posts/_navigation.html.erb
<nav class="top-bar" data-topbar role ="navigation">
	 <ul class="title-area">
		 <li class ="name">
		 	<h1>Formularios</h1>
		 </li>

	
	  </ul>
	   <section class="top-bar-section">
	   <ul>
	 <!-- Seccion Izquierda-->
		 <ul class="left">
 			<% if user_signed_in? %>
		 	<li class="has-dropdown not-click"><a href="#">Da click</a>
		 	<ul class="dropdown">
		 		<li class="parent-link show-for-small-only"> <a class="parent-link js-generated" href="#"></a></li>
		 			<li><label>Asesorias</label></li>
		 			<li><%=link_to 'Ver',controller:'/posts',action:'index'%></li>	
		 			<li><%=link_to 'Nuevo',controller:'/posts',action:'new'%></li>
		 	</ul>
		 	</li>
		 	<li class="divider"></li>
		 	<% end %> 
		 </ul>
		  
	 <!-- Seccion Derecha-->
	 <ul class="rigth">
	 	<% if user_signed_in? %>
	 	<li class="active"> <a href="#">Loogeado como <STRONG> <%= current_user.email   %></STRONG></a></li>
	 	<li> <%= link_to 'Edit Profile User', edit_user_registration_path , :class => 'navbar-link'%> </li>
	 	<li> <%= link_to "Logout User ",destroy_user_session_path ,method: :delete,:class => 'navbar-link'%></li>
	 		
	 	<% elsif admin_signed_in? %>
	 		<li class="active"> <a href="#">Loogeado como <STRONG> <%= current_admin.email   %></STRONG></a></li>
	 	<li> <%= link_to 'Edit Profile Admin', edit_admin_registration_path , :class => 'navbar-link'%> </li>
	 	<li> <%= link_to "Logout Admin ",destroy_admin_session_path ,method: :delete,:class => 'navbar-link'%>
	 	</li>
	 		

	 	<% else %>
	 	<li><%= link_to "Sing up",new_user_registration_path  ,:class=> 'navbar-link'%></li>
	 	<li><%= link_to "Login",new_user_session_path ,:class => 'navbar-link' %></li>
	 	<% end %>

	 </ul>
	
	 </section>
 </nav>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Titulo</th>
      <th>Body</th>
      <th>Usuario</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <% if post.body %>
        <td>        	
        	<a href="#" data-reveal-id="body-<%=post.id%>">Ver body</a>
        	<div id="body-<%=post.id%>" class="reveal-modal" data-reveal>
        	<%= post.body %>
        	<a class="close-reveal-modal">&#215;</a>
        	</div>	
        </td>
        <% end %>
        <% if admin_signed_in? %>
        
          <td> 
            <div>
          
              <%= User.find(post.user_id).email %>  
              
            </div>
          </td>
        <% end %>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? %>
  <%=  link_to 'New Post', new_post_path %>
<% end %>

app/views/posts/new.html.erb
<div class="row">
	<h1>Nuevo Post</h1>

	<%= render 'form' %>
	<div class="small-6 columns">
		<%= link_to 'Back', posts_path %>
	</div>
</div>

app/views/posts/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
</br>
<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>
</br>
<p>
  <strong>Categoria:</strong>
  <%= @post.categoria %>
</p>

<div id="comments">	
	<%= render :partial => @post.comments.reverse %>    
</div>

<%= form_for([@post,Comment.new],remote:true) do |f| %>
<p>
	<%= f.label :body,"Nuevo Comentario" %> <br/>
	<%= f.text_area :body%>
</p> 
<p>
	<%=f.submit "Agregar Comentario", :class => 'button small round' %>
</p>


<% end %>


<%= link_to 'Editar', edit_post_path(@post) %> |
<%= link_to 'Atras', posts_path %>